# 00. Python for PyTorch

PyTorch를 이용한 DL 실습을 위해.. 필요한 Python 문법을 **복습하기 위해 만든 노트북 파일입니다..**

## 학습 목표

이 노트북을 통해 아래의 내용을 익히며 Python 문법을 다시 복습하고 실습할 겁니다.

```python
class MyModel:
    def __init__(self, input_size):
        self.input_size = input_size

    def forward(self, x):
        return x.reshape(x.shape[0], -1)
```

전체 Python 문법을 다루지는 않고, **PyTorch 코드에서 자주 등장하는 내용**에 집중합니다.


---

## 0. 리스트, 튜플, 딕셔너리

딥러닝 코드에서는 여러 값을 묶어서 다루는 일이 많습니다.

### 리스트 `list`

- 순서가 있습니다.
- 값을 수정할 수 있습니다.
- 대괄호 `[]`를 사용합니다.


In [4]:
layers = [64, 128, 256]

print(layers)
print("첫 번째 값:", layers[0])
print("마지막 값:", layers[-1])

layers.append(512)
print("512 추가 후:", layers)

layers[0] = 32
print("첫 번째 값 수정 후:", layers)

[64, 128, 256]
첫 번째 값: 64
마지막 값: 256
512 추가 후: [64, 128, 256, 512]
첫 번째 값 수정 후: [32, 128, 256, 512]


### 인덱싱과 슬라이싱

Python 인덱스는 **0부터 시작**합니다.

```python
ex_list[start:end:step]
```

- start: 시작 인덱스
- end: 끝 인덱스, 단 포함되지 않음
- step: 몇 칸씩 이동할지 (양수이면 양수만큼 뛰어넘기, 음수이면 방향 거꾸로해서 뛰어넘기)

`끝` 위치의 원소는 포함하지 않습니다.


In [6]:
values = [10, 20, 30, 40, 50]

print(values[0])  # 10
print(values[1:4])  # [20, 30, 40]
print(values[:3])  # [10, 20, 30]
print(values[2:])  # [30, 40, 50]
print(values[::2])  # step이 2이므로 2칸씩 뛰어넘는다 → [10, 30, 50]
print(values[::-1])  # step이 -1이므로 방향이 거꾸로이다. → [50, 40, 30, 20, 10]
print(values[::-2])  # step이 -2이므로 뒤에서부터 -2칸씩 뛰어넘는다. → [50, 30, 10]

10
[20, 30, 40]
[10, 20, 30]
[30, 40, 50]
[10, 30, 50]
[50, 40, 30, 20, 10]
[50, 30, 10]


### 튜플 `tuple`

- 순서가 있습니다.
- 생성 후 값을 수정할 수 없습니다.
- 소괄호 `()`를 사용합니다.
- 이미지 크기나 텐서 크기를 표현할 때 자주 등장합니다.


In [ ]:
image_size = (224, 224)
tensor_shape = (32, 3, 224, 224)

print("이미지 크기:", image_size)  # (224, 224)
print("배치 크기:", tensor_shape[0])  # 32
print("채널 수:", tensor_shape[1])  # 3

이미지 크기: (224, 224)
배치 크기: 32
채널 수: 3


### 딕셔너리 `dict`

키와 값을 한 쌍으로 저장합니다.

학습 설정값, 모델 설정값, 데이터 샘플 등을 표현할 때 자주 사용합니다.


In [ ]:
config = {
    "model": "ResNet18",
    "batch_size": 32,
    "learning_rate": 0.001,
}

print(config)  # 전체 딕셔너리 츨력
print(config["model"])  # ResNet18
print(config["batch_size"])  # 32

config["epochs"] = 10  # 키:값 추가?
print(config)  # 업데이트 된 전체 딕셔너리 출력

{'model': 'ResNet18', 'batch_size': 32, 'learning_rate': 0.001}
ResNet18
32
{'model': 'ResNet18', 'batch_size': 32, 'learning_rate': 0.001, 'epochs': 10}


### 연습 문제 0

다음 정보를 가진 딕셔너리를 만들어 보세요.

- 모델 이름: `"Xception"`
- 배치 크기: `16`
- 클래스 수: `10`


In [9]:
model_config = {"model": "Xception", "batch_size": 16, "class_num": 10}

print(model_config)

{'model': 'Xception', 'batch_size': 16, 'class_num': 10}


---

## 1. 반복문

### `for` 반복문

데이터셋, 미니배치, 레이어 목록을 순회할 때 사용합니다.


In [10]:
layers = [64, 128, 256]

for channel in layers:
    print("출력 채널:", channel)

출력 채널: 64
출력 채널: 128
출력 채널: 256


In [11]:
# range(5)는 0, 1, 2, 3, 4를 생성합니다.
for epoch in range(5):
    print(f"Epoch {epoch + 1}/5")

Epoch 1/5
Epoch 2/5
Epoch 3/5
Epoch 4/5
Epoch 5/5


### `enumerate`

원소와 인덱스를 함께 가져올 때 사용합니다.


In [12]:
layers = ["Conv", "BatchNorm", "ReLU"]

for index, layer in enumerate(layers):
    print(index, layer)

0 Conv
1 BatchNorm
2 ReLU


### 리스트 컴프리헨션

반복문을 이용해 리스트를 간단하게 만드는 문법입니다.


In [ ]:
numbers = [1, 2, 3, 4, 5]

squares = [number**2 for number in numbers]

print(squares)

### 연습 문제 1

`range(1, 6)`을 이용해 `[10, 20, 30, 40, 50]`을 만들어 보세요.


In [13]:
result = [num * 10 for num in range(1, 6)]  # 리스트 컴프리헨션으로 수정하세요.

print(result)

[10, 20, 30, 40, 50]


---

## 2. 함수

함수는 반복해서 사용할 코드를 하나로 묶은 것입니다.

```python
def 함수이름(매개변수):
    실행할 코드
    return 반환값
```

### 매개변수와 인자

```python
def add(a, b):
    return a + b

add(2, 3)
```

- `a`, `b`: 함수 정의에 적힌 **매개변수(parameter)**
- `2`, `3`: 함수를 호출할 때 전달한 **인자(argument)**


In [14]:
# CNN shape 계산 공식 함수
def calculate_output_size(input_size, kernel_size, stride=1, padding=0):
    output_size = (input_size + 2 * padding - kernel_size) // stride + 1
    return output_size


result = calculate_output_size(
    input_size=32,
    kernel_size=3,
    stride=1,
    padding=1,
)

print(result)

32


### 기본값이 있는 매개변수

위 함수에서 `stride=1`, `padding=0`은 기본값입니다.

따라서 값을 전달하지 않으면 기본값이 사용됩니다.


In [15]:
print(calculate_output_size(32, 3))
print(calculate_output_size(32, 3, stride=2))
print(calculate_output_size(32, 3, stride=2, padding=1))

30
15
16


### 연습 문제 2

두 수를 받아 곱한 결과를 반환하는 `multiply` 함수를 작성하세요.


In [17]:
def multiply(a, b):
    result = a * b
    return result


print(multiply(3, 4))

12


---

## 3. 클래스, `self`, `__init__`

PyTorch 모델은 보통 클래스로 작성합니다.

```python
class MyModel:
    def __init__(self, input_size):
        self.input_size = input_size
```

### `self`

`self`는 **현재 생성된 객체 자기 자신**을 가리킵니다. (`Java`로 따지면 생성자 함수격이다.)

### `__init__`

객체를 생성할 때 자동으로 실행되는 초기화 메서드입니다.

### `input_size`

`input_size`는 객체를 만들 때 외부에서 전달받는 값입니다.

```python
model = MyModel(784)
```

이때 `784`가 `input_size`로 전달됩니다.


In [1]:
class SimpleModel:
    def __init__(self, input_size, output_size):
        self.input_size = input_size
        self.output_size = output_size

    def describe(self):
        print(f"입력 크기: {self.input_size}")
        print(f"출력 크기: {self.output_size}")


model = SimpleModel(input_size=784, output_size=10)

model.describe()

입력 크기: 784
출력 크기: 10


### 객체마다 값이 따로 저장됩니다

`self.input_size`는 각 객체 내부에 저장된 변수입니다.


In [2]:
model_a = SimpleModel(784, 10)
model_b = SimpleModel(2048, 1000)

model_a.describe()
print("---")
model_b.describe()

입력 크기: 784
출력 크기: 10
---
입력 크기: 2048
출력 크기: 1000


### 연습 문제 3

다음 조건을 만족하는 `TrainingConfig` 클래스를 작성하세요.

- `learning_rate`
- `epochs`
- 두 값을 출력하는 `show()` 메서드


In [3]:
class TrainingConfig:
    def __init__(self, learning_rate, epochs):
        self.learning_rate = learning_rate
        self.epochs = epochs

    def show(self):
        print(f"학습률: {self.learning_rate}")
        print(f"에폭: {self.epochs}")


config = TrainingConfig(learning_rate=0.001, epochs=10)
config.show()

학습률: 0.001
에폭: 10


---

## 4. 모듈 불러오기

다른 파일이나 라이브러리에 정의된 기능을 가져올 때 `import`를 사용합니다.


In [4]:
import math

print(math.sqrt(16))
print(math.pi)

4.0
3.141592653589793


In [5]:
from math import sqrt

print(sqrt(25))

5.0


PyTorch에서는 다음 형태를 자주 사용합니다.

```python
import torch
import torch.nn as nn
import torch.optim as optim
```

`as`는 모듈 이름을 짧은 별칭으로 사용하는 문법입니다.


---

## 5. NumPy 배열과 `shape`

PyTorch Tensor를 배우기 전에 NumPy 배열로 다차원 데이터의 형태를 익혀 봅니다.


In [1]:
import numpy as np

vector = np.array([1, 2, 3])
matrix = np.array(
    [
        [1, 2, 3],
        [4, 5, 6],
    ]
)

print("vector:", vector)
print("vector.shape:", vector.shape)

print("matrix:")
print(matrix)
print("matrix.shape:", matrix.shape)

vector: [1 2 3]
vector.shape: (3,)
matrix:
[[1 2 3]
 [4 5 6]]
matrix.shape: (2, 3)


### 이미지 배치의 shape

딥러닝 이미지 텐서는 보통 다음 순서입니다.

$$
(N, C, H, W)
$$

- $N$: 배치 크기
- $C$: 채널 수
- $H$: 높이
- $W$: 너비


In [ ]:
images = np.zeros(
    (32, 3, 224, 224)
)  # 입력받은 shape 모양대로 모든 원소가 0인 NumPy 배열을 생성하는 함수아다.

print(images.shape)
print("배치 크기:", images.shape[0])
print("채널 수:", images.shape[1])
print("높이:", images.shape[2])
print("너비:", images.shape[3])

(32, 3, 224, 224)
배치 크기: 32
채널 수: 3
높이: 224
너비: 224


---

## 6. `reshape`와 `-1`

배열의 원소 개수는 유지하면서 형태만 바꿉니다.


In [ ]:
x = np.arange(24)

print("변경 전:")
print(x)
print(x.shape)

x = x.reshape(
    2, 3, 4
)  # 크기가 3×4인 2차원 배열이 첫번째 축을 따라 2개 쌓인 3차원 배열을 의미

print("\n변경 후:")
print(x)
print(x.shape)

변경 전:
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]
(24,)

변경 후:
[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
(2, 3, 4)


### `-1`의 의미

**`-1`은 해당 차원의 크기를 Python/NumPy/PyTorch가 자동으로 계산하라는 뜻입니다.**


In [4]:
x = np.zeros((2, 3, 4))

print("원래 shape:", x.shape)

flattened = x.reshape(2, -1)

print("변경된 shape:", flattened.shape)

원래 shape: (2, 3, 4)
변경된 shape: (2, 12)


위 배열은 원래 `(2, 3, 4)`입니다.

첫 번째 차원 `2`는 유지하고 나머지 차원을 하나로 합치면:

$$
3 \times 4 = 12
$$

따라서 결과는 `(2, 12)`가 됩니다.

PyTorch에서 자주 보는 다음 코드도 같은 의미입니다.

```python
x = x.view(x.shape[0], -1)
```

즉, **배치 차원은 유지하고 나머지 차원을 모두 펼치는 것**입니다.


### 연습 문제 4

`(4, 3, 8, 8)` 배열을 배치 차원은 유지하면서 `(4, ?)` 형태로 펼쳐 보세요.

두 번째 차원의 크기도 예상해 보세요.


In [5]:
x = np.zeros((4, 3, 8, 8))

flattened = x.reshape(4, -1)  # 수정하세요.

print(flattened.shape)

(4, 192)


---

## 7. 언패킹

리스트나 튜플의 원소를 여러 변수에 나누어 저장할 수 있습니다.


In [6]:
shape = (32, 3, 224, 224)

batch_size, channels, height, width = shape

print(batch_size)
print(channels)
print(height)
print(width)

32
3
224
224


In [7]:
# *를 사용하면 나머지 값들을 묶어서 받을 수 있습니다.
first, *middle, last = [1, 2, 3, 4, 5]

print("first:", first)
print("middle:", middle)
print("last:", last)

first: 1
middle: [2, 3, 4]
last: 5


---

## 8. 자주 보는 Python 문법 모음


In [10]:
# None: 아직 값이 없음을 나타냅니다.
result = None
print(result)

# len(): 원소 개수를 반환합니다.
layers = [64, 128, 256]
print(len(layers))

# isinstance(): 자료형을 확인합니다.
print(isinstance(layers, list))

# f-string: 변수 값을 문자열 안에 넣습니다.
epoch = 3
loss = 0.12567
print(f"Epoch: {epoch}, Loss: {loss:.4f}")

None
3
True
Epoch: 3, Loss: 0.1257


---

## 9. 최종 확인 문제

다음 코드의 출력 shape를 실행 전에 예상해 보세요.


In [11]:
import numpy as np


class FlattenBatch:
    def __init__(self):
        self.name = "flatten"

    def forward(self, x):
        return x.reshape(x.shape[0], -1)


layer = FlattenBatch()
x = np.zeros((8, 3, 32, 32))
output = layer.forward(x)

print("입력 shape:", x.shape)  # (8, 3, 32, 32)
print("출력 shape:", output.shape)  # (8, 3072)

입력 shape: (8, 3, 32, 32)
출력 shape: (8, 3072)


---

## 정리

이번 노트북에서 다룬 핵심은 다음과 같습니다.

- 변수와 자료형
- 리스트, 튜플, 딕셔너리
- 조건문과 반복문
- 함수의 매개변수와 반환값
- 클래스, `self`, `__init__`
- NumPy 배열과 `shape`
- `reshape(..., -1)`
- PyTorch 모델 코드의 기본적인 읽는 방법

다음 단계에서는 **PyTorch Tensor의 생성, shape, dtype, device, indexing, reshape, 연산**을 다룹니다.
