# 01. Tensor Basics

PyTorch의 핵심 자료구조인 **Tensor**의 생성, 속성, 인덱싱, 형태 변환 및 기본 연산을 학습한다.

## 학습 목표

이 노트북을 완료하면 다음 내용을 설명하고 코드로 사용할 수 있다.

1. Tensor와 차원(`ndim`), 형태(`shape`)의 의미
2. 다양한 Tensor 생성 방법
3. `dtype`과 `device`
4. 인덱싱과 슬라이싱
5. `reshape`, `view`, `flatten`
6. `squeeze`, `unsqueeze`
7. `transpose`, `permute`
8. Tensor 간 기본 연산과 Broadcasting
9. NumPy 배열과 Tensor 간 변환
10. 이미지 Tensor의 `(N, C, H, W)` 구조

> 각 코드 셀을 위에서부터 순서대로 실행해 보자.


## 0. PyTorch 불러오기

PyTorch는 일반적으로 `torch`라는 이름으로 불러온다.


In [2]:
import torch

print("PyTorch version:", torch.__version__)

PyTorch version: 2.11.0+cu128


---

# 1. Tensor란?

Tensor는 숫자를 여러 차원으로 저장하는 자료구조이다.

|  차원 | 예시 shape     | 일반적인 이름 |
| ----: | -------------- | ------------- |
| 0차원 | `()`           | Scalar        |
| 1차원 | `(3,)`         | Vector        |
| 2차원 | `(2, 3)`       | Matrix        |
| 3차원 | `(2, 3, 4)`    | 3D Tensor     |
| 4차원 | `(2, 3, 4, 5)` | 4D Tensor     |

## 핵심

**Tensor의 차원 수는 `shape`에 들어 있는 숫자의 개수이다.**

예를 들어:

- `shape == (3,)` → 1차원
- `shape == (2, 3)` → 2차원
- `shape == (2, 3, 4)` → 3차원

`shape`에 있는 각 숫자는 해당 축(axis)의 크기를 의미한다.


In [3]:
scalar = torch.tensor(10)
vector = torch.tensor([10, 20, 30])
matrix = torch.tensor([[1, 2, 3], [4, 5, 6]])

print("scalar:", scalar)
print("vector:", vector)
print("matrix:\n", matrix)

scalar: tensor(10)
vector: tensor([10, 20, 30])
matrix:
 tensor([[1, 2, 3],
        [4, 5, 6]])


In [4]:
print("scalar ndim:", scalar.ndim)
print("scalar shape:", scalar.shape)

print("\nvector ndim:", vector.ndim)
print("vector shape:", vector.shape)

print("\nmatrix ndim:", matrix.ndim)
print("matrix shape:", matrix.shape)

scalar ndim: 0
scalar shape: torch.Size([])

vector ndim: 1
vector shape: torch.Size([3])

matrix ndim: 2
matrix shape: torch.Size([2, 3])


### `ndim`, `shape`, `size()`

- `tensor.ndim`: Tensor의 차원 수
- `tensor.shape`: 각 차원의 크기
- `tensor.size()`: `shape`과 같은 정보를 반환

`torch.Size([2, 3])`는 행이 2개이고, 각 행에 값이 3개 있다는 뜻이다.


In [5]:
print(matrix.shape)
print(matrix.size())

print("shape == size():", matrix.shape == matrix.size())

torch.Size([2, 3])
torch.Size([2, 3])
shape == size(): True


## 1-1. 3차원 Tensor 구조 읽기

아래 Tensor의 shape은 `(2, 2, 3)`이다.

바깥쪽부터 읽으면 다음과 같다.

- 큰 묶음이 2개
- 각 묶음 안에 행이 2개
- 각 행에 값이 3개


In [6]:
tensor_3d = torch.tensor([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

print(tensor_3d)
print("ndim:", tensor_3d.ndim)
print("shape:", tensor_3d.shape)

tensor([[[ 1,  2,  3],
         [ 4,  5,  6]],

        [[ 7,  8,  9],
         [10, 11, 12]]])
ndim: 3
shape: torch.Size([2, 2, 3])


### 연습 1

아래 Tensor의 `ndim`과 `shape`을 실행 전에 먼저 예상해 보자.


In [7]:
practice_1 = torch.tensor([[[1, 2], [3, 4], [5, 6]], [[7, 8], [9, 10], [11, 12]]])

# 실행 전에 먼저 예상해 보자.
print("ndim:", practice_1.ndim)  # 3
print("shape:", practice_1.shape)  # (2, 3, 2)

ndim: 3
shape: torch.Size([2, 3, 2])


<details>
<summary>정답 확인</summary>

- `ndim`: `3`
- `shape`: `(2, 3, 2)`

바깥 묶음 2개 × 각 묶음의 행 3개 × 각 행의 값 2개이다.

</details>


---

# 2. Tensor 생성하기


## 2-1. `torch.tensor()`

Python의 숫자나 리스트를 사용하여 Tensor를 만든다.


In [8]:
a = torch.tensor([1, 2, 3, 4])
b = torch.tensor([[1.0, 2.0], [3.0, 4.0]])

print(a)
print(b)

tensor([1, 2, 3, 4])
tensor([[1., 2.],
        [3., 4.]])


## 2-2. `torch.zeros()`, `torch.ones()`, `torch.full()`

- `torch.zeros(shape)`: 모든 값이 0
- `torch.ones(shape)`: 모든 값이 1
- `torch.full(shape, value)`: 모든 값을 지정한 값으로 채움


In [9]:
zeros = torch.zeros(2, 3)
ones = torch.ones(2, 3)
filled = torch.full((2, 3), 7)

print("zeros:\n", zeros)
print("\nones:\n", ones)
print("\nfilled:\n", filled)

zeros:
 tensor([[0., 0., 0.],
        [0., 0., 0.]])

ones:
 tensor([[1., 1., 1.],
        [1., 1., 1.]])

filled:
 tensor([[7, 7, 7],
        [7, 7, 7]])


## 2-3. `torch.arange()`

일정한 간격으로 증가하는 값을 만든다.

```python
torch.arange(start, end, step)
```

Python의 `range()`와 마찬가지로 **끝값 `end`는 포함하지 않는다.**


In [10]:
values_1 = torch.arange(0, 10)
values_2 = torch.arange(0, 10, 2)

print(values_1)
print(values_2)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
tensor([0, 2, 4, 6, 8])


## 2-4. `torch.linspace()`

linear space의 약자이다.

즉, 시작값과 끝값 사이를 선형적으로, 같은 간격으로 나눈 값들을 만든다는 뜻이다.

그래서, 시작값과 끝값 사이를 지정한 개수만큼 균등하게 나눈다.

```python
torch.linspace(start, end, steps)
```

`arange()`와 달리 **끝값을 포함한다.**


In [11]:
values = torch.linspace(0, 1, steps=5)
print(values)

tensor([0.0000, 0.2500, 0.5000, 0.7500, 1.0000])


## 2-5. 난수 Tensor

- `torch.rand()`: 0 이상 1 미만의 균등분포
- `torch.randn()`: 평균 0, 표준편차 1인 표준정규분포
- `torch.randint()`: 지정한 정수 범위에서 난수 생성


In [12]:
random_uniform = torch.rand(2, 3)
random_normal = torch.randn(2, 3)
random_integer = torch.randint(low=0, high=10, size=(2, 3))

print("rand:\n", random_uniform)
print("\nrandn:\n", random_normal)
print("\nrandint:\n", random_integer)

rand:
 tensor([[0.7736, 0.4331, 0.8419],
        [0.3693, 0.2603, 0.7231]])

randn:
 tensor([[ 1.3056, -0.3499, -1.4681],
        [-1.0696,  0.4065, -1.5887]])

randint:
 tensor([[6, 3, 6],
        [9, 7, 5]])


## 2-6. 난수 결과 고정하기

`torch.manual_seed()`를 사용하면 같은 난수 결과를 다시 생성할 수 있다.

난수 생성기(알고리즘)의 시작 상태(seed)를 42로 설정한 것이다.

머신러닝 실험의 **재현성**을 높이기 위해 자주 사용한다.


In [13]:
torch.manual_seed(42)  # 난수 생성기(알고리즘)의 시작 상태(seed)를 42로 설정한 것!
x1 = torch.rand(3)

torch.manual_seed(
    42
)  # 그래서 이걸 한 번더 선언하지 않으면 위에서 torch.rand(3)으로 난수 생성기의 알고리즘이 변했기 때문에 다른 결과가 나올 확률이 크다. 그래서, 한번 더 설정하는 것이다.
x2 = torch.rand(3)

print(x1)
print(x2)
print("같은 결과인가?", torch.equal(x1, x2))

tensor([0.8823, 0.9150, 0.3829])
tensor([0.8823, 0.9150, 0.3829])
같은 결과인가? True


### 연습 2

아래 빈칸을 채워 Tensor를 생성하자.


In [14]:
# 1. [1, 2, 3, 4, 5]를 저장한 1차원 Tensor
tensor_a = torch.arange(1, 6)
tensor_a = torch.range(1, 5)
tensor_a = torch.tensor([1, 2, 3, 4, 5])

# 2. shape이 (3, 4)이고 모든 값이 0인 Tensor
tensor_b = torch.zeros(3, 4)

# 3. shape이 (2, 3, 4)이고 모든 값이 1인 Tensor
tensor_c = torch.ones(2, 3, 4)

# 4. 0부터 20 미만까지 5씩 증가하는 Tensor
tensor_d = torch.arange(0, 20, 5)

# 5. -1부터 1까지 총 5개의 값으로 나눈 Tensor
tensor_e = torch.linspace(-1, 1, steps=5)

print("tensor_a:", tensor_a)
print("tensor_b:", tensor_b)
print("tensor_c:", tensor_c)
print("tensor_d:", tensor_d)
print("tensor_e:", tensor_e)

tensor_a: tensor([1, 2, 3, 4, 5])
tensor_b: tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])
tensor_c: tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])
tensor_d: tensor([ 0,  5, 10, 15])
tensor_e: tensor([-1.0000, -0.5000,  0.0000,  0.5000,  1.0000])


/tmp/ipykernel_10622/1942778247.py:3: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  tensor_a = torch.range(1, 5)


<details>
<summary>정답 확인</summary>

```python
tensor_a = torch.tensor([1, 2, 3, 4, 5])
tensor_b = torch.zeros(3, 4)
tensor_c = torch.ones(2, 3, 4)
tensor_d = torch.arange(0, 20, 5)
tensor_e = torch.linspace(-1, 1, steps=5)
```

</details>


---

# 3. Tensor의 핵심 속성: `shape`, `dtype`, `device`

PyTorch Tensor를 사용할 때 자주 확인해야 하는 세 가지 속성이다.

- `shape`: Tensor의 형태
- `dtype`: 원소의 자료형
- `device`: Tensor가 저장된 연산 장치


In [15]:
x = torch.tensor([[1.0, 2.0], [3.0, 4.0]])

print("shape:", x.shape)
print("dtype:", x.dtype)
print("device:", x.device)

shape: torch.Size([2, 2])
dtype: torch.float32
device: cpu


## 3-1. `dtype`

대표적인 자료형은 다음과 같다.

| PyTorch dtype   | 의미        |
| --------------- | ----------- |
| `torch.float32` | 32비트 실수 |
| `torch.float64` | 64비트 실수 |
| `torch.int64`   | 64비트 정수 |
| `torch.int32`   | 32비트 정수 |
| `torch.bool`    | 참/거짓     |

딥러닝에서는 입력과 가중치에 일반적으로 `float32`를 사용한다.


In [16]:
int_tensor = torch.tensor([1, 2, 3])
float_tensor = torch.tensor([1.0, 2.0, 3.0])
explicit_float = torch.tensor([1, 2, 3], dtype=torch.float32)

print(int_tensor.dtype)
print(float_tensor.dtype)
print(explicit_float.dtype)

torch.int64
torch.float32
torch.float32


## 3-2. 자료형 변환

다음 방법을 사용할 수 있다.

- `x.float()`
- `x.long()`
- `x.bool()`
- `x.to(dtype=...)`


In [17]:
x = torch.tensor([1, 2, 3])

x_float = x.float()
x_float_2 = x.to(dtype=torch.float32)

print(x.dtype)
print(x_float.dtype)
print(x_float_2.dtype)

torch.int64
torch.float32
torch.float32


## 3-3. `device`

Tensor는 일반적으로 다음 장치에 저장된다.

- CPU: `"cpu"`
- NVIDIA GPU: `"cuda"`
- Apple Silicon GPU: `"mps"`

현재 환경에서 사용할 수 있는 장치를 자동으로 선택해 보자.


In [18]:
if torch.cuda.is_available():
    device = torch.device("cuda")
elif hasattr(torch.backends, "mps") and torch.backends.mps.is_available():
    device = torch.device("mps")
else:
    device = torch.device("cpu")

print("사용 장치:", device)

사용 장치: cuda


In [19]:
x = torch.tensor([1.0, 2.0, 3.0])
x_on_device = x.to(device)

print("원래 device:", x.device)
print("이동 후 device:", x_on_device.device)

원래 device: cpu
이동 후 device: cuda:0


> 연산에 참여하는 Tensor들은 일반적으로 같은 `device`에 있어야 한다.


---

# 4. 인덱싱과 슬라이싱

Tensor의 인덱싱은 Python 리스트와 NumPy 배열의 방식과 비슷하다.


In [20]:
x = torch.tensor([[10, 20, 30], [40, 50, 60], [70, 80, 90]])

print(x)

tensor([[10, 20, 30],
        [40, 50, 60],
        [70, 80, 90]])


In [21]:
print("첫 번째 행:", x[0])  # [10, 20, 30]
print("두 번째 행:", x[1])  # [40, 50, 60]
print("1행 2열의 값:", x[0, 1])  # 20
print("마지막 행:", x[-1])  # [70, 80, 90]

첫 번째 행: tensor([10, 20, 30])
두 번째 행: tensor([40, 50, 60])
1행 2열의 값: tensor(20)
마지막 행: tensor([70, 80, 90])


## 슬라이싱

`start:end:step` 형식을 사용한다.

끝 인덱스 `end`는 포함하지 않는다.


In [22]:
print("앞의 두 행:\n", x[:2])
print("\n두 번째 열 이후:\n", x[:, 1:])
print("\n모든 행의 첫 번째 열:", x[:, 0])
print("\n행을 역순으로 선택:\n", x.flip(0))

앞의 두 행:
 tensor([[10, 20, 30],
        [40, 50, 60]])

두 번째 열 이후:
 tensor([[20, 30],
        [50, 60],
        [80, 90]])

모든 행의 첫 번째 열: tensor([10, 40, 70])

행을 역순으로 선택:
 tensor([[70, 80, 90],
        [40, 50, 60],
        [10, 20, 30]])


### `x[:, 0]` 해석

- `:` → 첫 번째 축의 모든 원소
- `0` → 두 번째 축의 0번 원소

따라서 모든 행에서 첫 번째 열만 선택한다.


## 4-1. Boolean Mask

조건을 만족하는 원소만 선택할 수 있다.


In [23]:
x = torch.tensor([1, 2, 3, 4, 5, 6])

mask = x > 3

print("mask:", mask)
print("3보다 큰 값:", x[mask])

mask: tensor([False, False, False,  True,  True,  True])
3보다 큰 값: tensor([4, 5, 6])


### 연습 3

아래 Tensor에서 원하는 값을 선택하자.


In [24]:
x = torch.tensor([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

# 1. 두 번째 행을 선택
answer_1 = x[1]

# 2. 모든 행에서 마지막 두 열을 선택
answer_2 = x[
    :, -2:
]  # [:, -2:] 이므로, 첫번째 축에서 `:`로 모든 것을 고르고(모든 행), 2번째 축(열)에서 `-2:`로 -2열부터 끝까지 마지막 두 열을 선택할 수 있다.

# 3. 값이 6보다 큰 원소만 선택
answer_3 = x[x > 6]

print(answer_1)
print(answer_2)
print(answer_3)

tensor([5, 6, 7, 8])
tensor([[ 3,  4],
        [ 7,  8],
        [11, 12]])
tensor([ 7,  8,  9, 10, 11, 12])


<details>
<summary>정답 확인</summary>

```python
answer_1 = x[1]
answer_2 = x[:, -2:]
answer_3 = x[x > 6]
```

</details>


---

# 5. Tensor의 형태 변경

원소 자체는 유지하면서 Tensor의 `shape`을 변경할 수 있다.


## 5-1. `reshape()`

전체 원소 개수가 같아야 한다.

예를 들어 원소가 12개인 Tensor는 다음 형태로 바꿀 수 있다.

- `(12,)`
- `(3, 4)`
- `(2, 6)`
- `(2, 2, 3)`


In [25]:
x = torch.arange(12)

print("원본:", x)
print("원본 shape:", x.shape)

x_3x4 = x.reshape(3, 4)
x_2x2x3 = x.reshape(2, 2, 3)

print("\n(3, 4):\n", x_3x4)
print("shape:", x_3x4.shape)

print("\n(2, 2, 3):\n", x_2x2x3)
print("shape:", x_2x2x3.shape)

원본: tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])
원본 shape: torch.Size([12])

(3, 4):
 tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])
shape: torch.Size([3, 4])

(2, 2, 3):
 tensor([[[ 0,  1,  2],
         [ 3,  4,  5]],

        [[ 6,  7,  8],
         [ 9, 10, 11]]])
shape: torch.Size([2, 2, 3])


## 5-2. `-1`을 사용한 자동 계산

`reshape()`에서 한 차원에 `-1`을 넣으면 나머지 차원의 크기를 기준으로 PyTorch가 자동 계산한다.


In [26]:
x = torch.arange(24)

a = x.reshape(2, 3, -1)
b = x.reshape(4, -1)

print("a shape:", a.shape)
print("b shape:", b.shape)

a shape: torch.Size([2, 3, 4])
b shape: torch.Size([4, 6])


### `x.reshape(2, 3, -1)` 계산

전체 원소 수가 24개이고 앞의 두 차원이 `2 × 3`이므로:

$$
2 \times 3 \times ? = 24
$$

따라서 마지막 차원은 4가 된다.

$$
? = \frac{24}{2 \times 3} = 4
$$

결과 shape은 `(2, 3, 4)`이다.


## 5-3. `view()`

`view()`는 Tensor의 원소 개수는 유지하면서 shape을 변경한 새로운 Tensor를 반환한다.

```python
x.view(new_shape)
```

다만 `view()`는 메모리에 연속적으로 저장된 Tensor에서만 바로 동작한다. 입문 단계에서는 보통 `reshape()`가 더 안전하다.

<details>
<summary>“메모리에 연속적으로 저장된 Tensor에서만 바로 동작한다”는 것은 무슨 의미일까?</summary>

### 1. Tensor는 값뿐만 아니라 shape과 stride를 함께 가진다

화면에서는 Tensor가 다음과 같은 2차원 행렬로 보인다.

$$
A=
\begin{bmatrix}
1 & 2 & 3\\
4 & 5 & 6
\end{bmatrix}
$$

하지만 실제 원소들은 메모리의 1차원 저장 공간인 **Storage**에 다음과 같이 저장된다.

$$
[1,\ 2,\ 3,\ 4,\ 5,\ 6]
$$

Tensor는 이 1차원 Storage를 다음 정보를 이용하여 다차원으로 해석한다.

- **shape**: 각 차원의 크기
- **stride**: 특정 차원에서 인덱스를 1 증가시킬 때 Storage에서 몇 칸 이동하는지
- **storage offset**: Storage에서 Tensor의 첫 번째 원소가 시작되는 위치

---

### 2. 원본 Tensor의 stride

원본 Tensor $A$의 shape은 다음과 같다.

$$
\operatorname{shape}(A)=(2,3)
$$

Storage에서 다음 열로 이동하려면 한 칸을 이동해야 한다.

$$
\operatorname{stride}[1]=1
$$

다음 행으로 이동하려면 세 칸을 이동해야 한다.

$$
\operatorname{stride}[0]=3
$$

따라서 $A$의 stride는 다음과 같다.

$$
\operatorname{stride}(A)=(3,1)
$$

2차원 Tensor에서 위치 $(i,j)$의 원소가 저장된 Storage 위치는 다음과 같이 계산할 수 있다.

$$
\text{Storage Index}
=
\text{offset}
+i \times \text{stride}[0]
+j \times \text{stride}[1]
$$

예를 들어 $A[1,2]=6$의 Storage 위치는 다음과 같다.

$$
0 + 1 \times 3 + 2 \times 1 = 5
$$

Storage의 5번 인덱스에는 값 `6`이 저장되어 있다.

---

### 3. `transpose()`는 데이터를 바로 재배치하지 않는다

```python
x_t = x.transpose(0, 1)
```

`transpose()`는 두 차원의 위치를 교환한다.

$$
A^T=
\begin{bmatrix}
1 & 4\\
2 & 5\\
3 & 6
\end{bmatrix}
$$

이때 shape은 다음과 같이 바뀐다.

$$
(2,3)\rightarrow(3,2)
$$

하지만 Storage의 원소 순서는 그대로 유지된다.

$$
[1,\ 2,\ 3,\ 4,\ 5,\ 6]
$$

대신 각 차원을 이동하는 방법인 stride가 교환된다.

$$
(3,1)\rightarrow(1,3)
$$

따라서 `transpose()` 직후의 정보는 다음과 같다.

| Tensor              | 화면에 보이는 shape |   stride | 실제 Storage         |
| ------------------- | ------------------: | -------: | -------------------- |
| `x`                 |            `(2, 3)` | `(3, 1)` | `[1, 2, 3, 4, 5, 6]` |
| `x.transpose(0, 1)` |            `(3, 2)` | `(1, 3)` | `[1, 2, 3, 4, 5, 6]` |

즉, `transpose()`는 일반적으로 데이터를 복사하지 않고, 같은 Storage를 다른 shape과 stride로 해석하는 **View 연산**이다.

```python
x = torch.tensor([
    [1, 2, 3],
    [4, 5, 6]
])

x_t = x.transpose(0, 1)

print(x.shape)       # torch.Size([2, 3])
print(x.stride())    # (3, 1)

print(x_t.shape)     # torch.Size([3, 2])
print(x_t.stride())  # (1, 3)
```

---

### 4. 왜 transpose한 Tensor는 non-contiguous한가?

원본 `x`는 화면에서 읽는 순서와 Storage에 저장된 순서가 같다.

$$
1\rightarrow2\rightarrow3\rightarrow4\rightarrow5\rightarrow6
$$

따라서 메모리에 연속적인 `contiguous` Tensor이다.

하지만 전치된 `x_t`를 화면에서 행 단위로 읽으면 다음과 같다.

$$
1\rightarrow4\rightarrow2\rightarrow5\rightarrow3\rightarrow6
$$

실제 Storage의 순서인

$$
1\rightarrow2\rightarrow3\rightarrow4\rightarrow5\rightarrow6
$$

와 일치하지 않는다.

따라서 `x_t`는 일반적인 행 우선 순서에서 메모리가 연속적이지 않은 **non-contiguous Tensor**가 된다.

```python
print(x.is_contiguous())    # True
print(x_t.is_contiguous())  # False
```

---

### 5. 이 상태에서 `view()`가 실패하는 이유

`view()`는 기존 Storage를 그대로 사용하면서 새로운 shape으로 해석한다.

그런데 전치된 `x_t`는 화면에서 원소가 나열되는 순서와 실제 Storage 순서가 다르다.

따라서 다음과 같이 1차원으로 변경하려 하면 오류가 발생한다.

```python
x_t.view(-1)
```

`x_t`를 화면에 보이는 순서대로 펼치려면 다음 결과가 필요하다.

```python
tensor([1, 4, 2, 5, 3, 6])
```

하지만 실제 Storage는 다음 순서이다.

```python
[1, 2, 3, 4, 5, 6]
```

`view()`는 데이터를 복사하거나 재배치하지 않으므로 이 차이를 해결할 수 없다.

> 엄밀하게 말하면 `view()`가 모든 non-contiguous Tensor에서 실패하는 것은 아니다.
> 현재 shape과 stride가 요청한 shape과 호환된다면 동작할 수도 있다.
> 다만 `transpose()` 이후 여러 차원을 하나로 합치는 경우에는 일반적으로 실패한다.

---

### 6. `contiguous()`를 사용하면 어떻게 될까?

```python
x_c = x_t.contiguous()
```

`contiguous()`는 화면에 보이는 원소 순서에 맞춰 데이터를 새로운 Storage에 복사한다.

기존 Storage:

$$
[1,\ 2,\ 3,\ 4,\ 5,\ 6]
$$

새로운 Storage:

$$
[1,\ 4,\ 2,\ 5,\ 3,\ 6]
$$

이제 shape이 `(3, 2)`인 연속적인 Tensor이므로 stride는 다음과 같다.

$$
\operatorname{stride}(x_c)=(2,1)
$$

```python
x_c = x_t.contiguous()

print(x_c)
# tensor([
#     [1, 4],
#     [2, 5],
#     [3, 6]
# ])

print(x_c.stride())         # (2, 1)
print(x_c.is_contiguous())  # True

print(x_c.view(-1))
# tensor([1, 4, 2, 5, 3, 6])
```

따라서 stride가 `(2,1)`이고 Storage가 `[1,4,2,5,3,6]`인 그림은 단순한 `A.T`가 아니라 다음 상태를 나타낸다고 보는 것이 정확하다.

```python
A.T.contiguous()
```

---

### 7. `view()`와 `reshape()`의 차이

#### `view()`

- 기존 Storage를 그대로 공유한다.
- 데이터를 복사하지 않는다.
- 현재 shape과 stride가 새로운 shape과 호환되어야 한다.
- 호환되지 않으면 오류가 발생한다.

```python
x_t.view(-1)  # 오류 발생 가능
```

#### `reshape()`

- 먼저 복사 없이 View로 변경할 수 있는지 확인한다.
- 가능하면 기존 Storage를 공유한다.
- 불가능하면 필요한 데이터를 새로운 연속적인 Storage에 복사한다.
- 따라서 사용하기는 편하지만, 내부에서 복사가 발생할 수 있다.

```python
x_t.reshape(-1)
# tensor([1, 4, 2, 5, 3, 6])
```

이 예제에서 `reshape()`는 개념적으로 다음과 비슷하게 동작한다.

```python
x_t.contiguous().view(-1)
```

다만 `reshape()`가 실제로 View를 반환할지 복사본을 반환할지는 Tensor의 메모리 배치에 따라 달라지므로, 코드에서 그 동작 방식에 의존해서는 안 된다.

---

### 핵심 정리

```text
transpose()
    shape과 stride를 교환한다.
    일반적으로 데이터를 복사하지 않는다.
    결과가 non-contiguous해질 수 있다.

view()
    데이터를 복사하지 않는다.
    현재 Storage와 stride로 표현 가능한 shape만 만들 수 있다.

contiguous()
    non-contiguous Tensor를 연속적인 메모리 배치로 복사한다.

reshape()
    가능하면 View를 반환한다.
    불가능하면 데이터를 복사하여 새로운 Tensor를 만든다.
```

</details>


In [27]:
x = torch.arange(12)

print(x.view(3, 4))
print(x.reshape(3, 4))

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])
tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])


## 5-4. `flatten()`

여러 차원의 Tensor를 1차원으로 펼친다.


In [28]:
x = torch.arange(12).reshape(3, 4)

flattened = x.flatten()

print("원본 shape:", x.shape)
print("flatten 결과:", flattened)
print("flatten shape:", flattened.shape)

원본 shape: torch.Size([3, 4])
flatten 결과: tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])
flatten shape: torch.Size([12])


딥러닝 모델에서는 배치 차원을 유지하고 나머지 차원만 펼치는 경우가 많다.


In [29]:
x = torch.randn(2, 3, 4, 4)

flattened = x.flatten(
    start_dim=1
)  # 1번째 인덱스의 차원(2번째 차원)부터 마지막 차원까지 평탄화 시킨다. 그래서, 0이면 첫번째 차원부터 마지막 차원까지 다 평탄화가 된다.

print("원본 shape:", x.shape)
print("변환 shape:", flattened.shape)

원본 shape: torch.Size([2, 3, 4, 4])
변환 shape: torch.Size([2, 48])


위 예시에서 배치 크기 2는 유지되고, 나머지 `3 × 4 × 4 = 48`개 값이 하나의 차원으로 합쳐졌다.

$$
(2, 3, 4, 4) \rightarrow (2, 48)
$$


### 연습 4

원소가 24개인 Tensor의 shape을 변경하자.


In [30]:
x = torch.arange(24)

# 1. shape을 (4, 6)으로 변경
answer_1 = x.view(4, 6)

# 2. shape을 (2, 3, 4)로 변경
answer_2 = x.reshape(2, 3, 4)

# 3. 첫 번째 차원을 3으로 지정하고 나머지는 자동 계산
answer_3 = x.reshape(3, -1).flatten(start_dim=1)

print(answer_1.shape)
print(answer_2.shape)
print(answer_3.shape)

torch.Size([4, 6])
torch.Size([2, 3, 4])
torch.Size([3, 8])


<details>
<summary>정답 확인</summary>

```python
answer_1 = x.reshape(4, 6)
answer_2 = x.reshape(2, 3, 4)
answer_3 = x.reshape(3, -1)
```

</details>


---

# 6. 차원 추가와 제거

## 6-1. `unsqueeze()`

크기가 1인 새로운 차원을 추가한다.


In [31]:
x = torch.tensor([10, 20, 30])

print("원본 shape:", x.shape)

print("unsqueeze(0):", x.unsqueeze(0).shape)

print("unsqueeze(1):", x.unsqueeze(1).shape)

원본 shape: torch.Size([3])
unsqueeze(0): torch.Size([1, 3])
unsqueeze(1): torch.Size([3, 1])


구조는 다음과 같이 변한다.

- `(3,)`
- `unsqueeze(0)` → `(1, 3)`
- `unsqueeze(1)` → `(3, 1)`

추가되는 차원의 위치가 다르다.


In [32]:
print("unsqueeze(0):\n", x.unsqueeze(0))
print("\nunsqueeze(1):\n", x.unsqueeze(1))

unsqueeze(0):
 tensor([[10, 20, 30]])

unsqueeze(1):
 tensor([[10],
        [20],
        [30]])


## 6-2. `squeeze()`

크기가 1인 차원을 제거한다.


In [33]:
x = torch.zeros(1, 3, 1, 4)

print("원본 shape:", x.shape)
print("squeeze 결과:", x.squeeze().shape)
print("squeeze(0) 결과:", x.squeeze(0).shape)
print("squeeze(2) 결과:", x.squeeze(2).shape)

원본 shape: torch.Size([1, 3, 1, 4])
squeeze 결과: torch.Size([3, 4])
squeeze(0) 결과: torch.Size([3, 1, 4])
squeeze(2) 결과: torch.Size([1, 3, 4])


> `squeeze()`는 크기가 1인 차원만 제거할 수 있다.


### 이미지 한 장에 배치 차원 추가하기

CNN은 일반적으로 `(N, C, H, W)` 형태의 입력을 받는다.

이미지 한 장의 shape이 `(C, H, W)`라면 `unsqueeze(0)`으로 배치 차원을 추가할 수 있다.


In [34]:
image = torch.randn(3, 224, 224)

batched_image = image.unsqueeze(0)

print("한 장의 이미지:", image.shape)
print("배치 차원 추가:", batched_image.shape)

한 장의 이미지: torch.Size([3, 224, 224])
배치 차원 추가: torch.Size([1, 3, 224, 224])


---

# 7. 축의 순서 변경

## 7-1. `transpose()`

두 개의 차원을 서로 교환한다.


In [ ]:
x = torch.arange(6).reshape(2, 3)

print("원본:\n", x)
print("원본 shape:", x.shape)

x_t = x.transpose(0, 1)  # 0번째 차원과 1번째 차원을 교환한다는 뜻.

print("\ntranspose 결과:\n", x_t)
print("결과 shape:", x_t.shape)

원본:
 tensor([[0, 1, 2],
        [3, 4, 5]])
원본 shape: torch.Size([2, 3])

transpose 결과:
 tensor([[0, 3],
        [1, 4],
        [2, 5]])
결과 shape: torch.Size([3, 2])


2차원 행렬에서는 `x.T`도 사용할 수 있다.


In [36]:
print(x.T)

tensor([[0, 3],
        [1, 4],
        [2, 5]])


3차원 이상 행렬에서도 인수에 들어가는 두 행을 교환한다.

```python
x = torch.randn(2, 3, 4)
```

이면, 각 차원 번호는

- dim=0 → 크기 2
- dim=1 → 크기 3
- dim=2 → 크기 4

이다.

```python
y = x.transpose(0, 2)
```

을 하면, 이면 0번 축과 2번 축을 바꾸므로,

```
(2, 3, 4) → (4, 3, 2)
```

가 된다.


In [68]:
x = torch.arange(24).view(2, 3, 4)

print("원본:\n", x)
print("원본 shape:", x.shape)

x_t = x.transpose(0, 2)  # 0번째 차원과 2번째 차원을 교환한다는 뜻.

print("\ntranspose 결과:\n", x_t)
print("결과 shape:", x_t.shape)

원본:
 tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],

        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]])
원본 shape: torch.Size([2, 3, 4])

transpose 결과:
 tensor([[[ 0, 12],
         [ 4, 16],
         [ 8, 20]],

        [[ 1, 13],
         [ 5, 17],
         [ 9, 21]],

        [[ 2, 14],
         [ 6, 18],
         [10, 22]],

        [[ 3, 15],
         [ 7, 19],
         [11, 23]]])
결과 shape: torch.Size([4, 3, 2])


## 7-2. `permute()`

여러 차원의 순서를 한 번에 재배치한다.


In [37]:
x = torch.randn(2, 3, 4)

print("원본 shape:", x.shape)

y = x.permute(2, 0, 1)

print("변환 shape:", y.shape)

원본 shape: torch.Size([2, 3, 4])
변환 shape: torch.Size([4, 2, 3])


`x.permute(2, 0, 1)`은 기존 축의 순서를 다음처럼 바꾼다.

- 기존 2번 축 → 새로운 0번 축
- 기존 0번 축 → 새로운 1번 축
- 기존 1번 축 → 새로운 2번 축

따라서:

$$
(2, 3, 4) \rightarrow (4, 2, 3)
$$


## 이미지 Tensor의 축 순서 변경

이미지 라이브러리나 TensorFlow에서는 이미지를 `(H, W, C)`로 다루는 경우가 많다.

PyTorch CNN은 일반적으로 `(C, H, W)`를 사용하므로 다음과 같이 변환한다.


In [38]:
image_hwc = torch.randn(224, 224, 3)

image_chw = image_hwc.permute(2, 0, 1)

print("HWC:", image_hwc.shape)
print("CHW:", image_chw.shape)

HWC: torch.Size([224, 224, 3])
CHW: torch.Size([3, 224, 224])


### 연습 5

`(N, H, W, C)` 형식의 이미지 배치를 PyTorch의 `(N, C, H, W)` 형식으로 바꾸자.


In [70]:
images_nhwc = torch.randn(8, 32, 32, 3)

# (8, 32, 32, 3) -> (8, 3, 32, 32)
images_nchw = images_nhwc.permute(0, 3, 1, 2)

print(images_nchw.shape if images_nchw is not None else None)

torch.Size([8, 3, 32, 32])


<details>
<summary>정답 확인</summary>

```python
images_nchw = images_nhwc.permute(0, 3, 1, 2)
```

축의 순서를 다음과 같이 지정한다.

- 0번 축 `N` 유지
- 3번 축 `C`를 두 번째로 이동
- 1번 축 `H`
- 2번 축 `W`

</details>


---

# 8. Tensor 기본 연산


In [40]:
a = torch.tensor([1.0, 2.0, 3.0])
b = torch.tensor([4.0, 5.0, 6.0])

print("덧셈:", a + b)
print("뺄셈:", a - b)
print("원소별 곱셈:", a * b)
print("원소별 나눗셈:", a / b)
print("제곱:", a**2)

덧셈: tensor([5., 7., 9.])
뺄셈: tensor([-3., -3., -3.])
원소별 곱셈: tensor([ 4., 10., 18.])
원소별 나눗셈: tensor([0.2500, 0.4000, 0.5000])
제곱: tensor([1., 4., 9.])


## 8-1. 원소별 곱셈과 행렬 곱셈의 차이

- `a * b`: 같은 위치의 원소끼리 곱함
- `a @ b` 또는 `torch.matmul(a, b)`: 행렬 곱셈


In [ ]:
a = torch.tensor(
  [[1.0, 2.0],
  [3.0, 4.0]]
  )

b = torch.tensor(
  [[5.0, 6.0],
  [7.0, 8.0]]
  )

print("원소별 곱셈:\n", a * b)
print("\n행렬 곱셈:\n", a @ b)

원소별 곱셈:
 tensor([[ 5., 12.],
        [21., 32.]])

행렬 곱셈:
 tensor([[19., 22.],
        [43., 50.]])


행렬 곱셈에서 shape은 다음 조건을 만족해야 한다.

$$
(m, n) @ (n, p) \rightarrow (m, p)
$$

첫 번째 행렬의 열 수와 두 번째 행렬의 행 수가 같아야 한다.


## 8-2. 집계 연산

Tensor 전체 또는 특정 축을 따라 값을 집계할 수 있다.


In [42]:
x = torch.tensor([[1.0, 2.0, 3.0], [4.0, 5.0, 6.0]])

print("전체 합:", x.sum())
print("전체 평균:", x.mean())
print("최댓값:", x.max())
print("최솟값:", x.min())

print("\n열 방향 합(dim=0):", x.sum(dim=0))
print("행 방향 합(dim=1):", x.sum(dim=1))

전체 합: tensor(21.)
전체 평균: tensor(3.5000)
최댓값: tensor(6.)
최솟값: tensor(1.)

열 방향 합(dim=0): tensor([5., 7., 9.])
행 방향 합(dim=1): tensor([ 6., 15.])


### `dim` 이해하기

shape이 `(2, 3)`인 Tensor에서:

- `dim=0`: 0번 축을 없애면서 계산 → 결과 shape `(3,)`
- `dim=1`: 1번 축을 없애면서 계산 → 결과 shape `(2,)`

즉, 지정한 `dim` 방향으로 값을 모아서 계산한다.


In [43]:
print("원본 shape:", x.shape)
print("sum(dim=0) shape:", x.sum(dim=0).shape)
print("sum(dim=1) shape:", x.sum(dim=1).shape)

원본 shape: torch.Size([2, 3])
sum(dim=0) shape: torch.Size([3])
sum(dim=1) shape: torch.Size([2])


## 8-3. `keepdim=True`

집계한 축을 제거하지 않고 크기 1로 유지한다.


In [44]:
print(x.sum(dim=1))
print(x.sum(dim=1, keepdim=True))

print("keepdim=False:", x.sum(dim=1).shape)
print("keepdim=True:", x.sum(dim=1, keepdim=True).shape)

tensor([ 6., 15.])
tensor([[ 6.],
        [15.]])
keepdim=False: torch.Size([2])
keepdim=True: torch.Size([2, 1])


---

# 9. Broadcasting

shape이 완전히 같지 않더라도 일정한 규칙을 만족하면 PyTorch가 작은 Tensor를 자동으로 확장하여 연산한다.


In [45]:
x = torch.tensor([[1.0, 2.0, 3.0], [4.0, 5.0, 6.0]])

bias = torch.tensor([10.0, 20.0, 30.0])

print("x shape:", x.shape)
print("bias shape:", bias.shape)
print("\n결과:\n", x + bias)

x shape: torch.Size([2, 3])
bias shape: torch.Size([3])

결과:
 tensor([[11., 22., 33.],
        [14., 25., 36.]])


`x`의 shape은 `(2, 3)`, `bias`의 shape은 `(3,)`이다.

PyTorch는 `bias`를 각 행에 반복 적용한 것처럼 계산한다.

$$
\begin{bmatrix}
1 & 2 & 3 \\
4 & 5 & 6
\end{bmatrix}
+
\begin{bmatrix}
10 & 20 & 30
\end{bmatrix}
=
\begin{bmatrix}
11 & 22 & 33 \\
14 & 25 & 36
\end{bmatrix}
$$


## Broadcasting의 기본 규칙

오른쪽 끝 차원부터 비교한다.

두 차원의 크기가 다음 중 하나라면 연산할 수 있다.

1. 두 크기가 같다.
2. 둘 중 하나가 1이다.
3. 한쪽에 해당 차원이 없다.

예:

- `(2, 3)`과 `(3,)` → 가능
- `(2, 3)`과 `(1, 3)` → 가능
- `(2, 3)`과 `(2, 1)` → 가능
- `(2, 3)`과 `(2,)` → 불가능


In [46]:
a = torch.ones(2, 3)
b = torch.tensor([[10.0], [20.0]])

print("a shape:", a.shape)
print("b shape:", b.shape)
print(a + b)

a shape: torch.Size([2, 3])
b shape: torch.Size([2, 1])
tensor([[11., 11., 11.],
        [21., 21., 21.]])


### 연습 6

각 행에서 해당 행의 평균을 빼서 평균이 0이 되도록 만들자.

힌트:

1. `mean(dim=1, keepdim=True)`로 각 행의 평균을 구한다.
2. 원본 Tensor에서 평균을 뺀다.


In [75]:
x = torch.tensor([[1.0, 2.0, 3.0], [10.0, 20.0, 30.0]])

row_mean = x.mean(dim=1, keepdim=True)
centered = x - row_mean

print("각 행의 평균:\n", row_mean)
print("\n평균을 뺀 결과:\n", centered)

각 행의 평균:
 tensor([[ 2.],
        [20.]])

평균을 뺀 결과:
 tensor([[ -1.,   0.,   1.],
        [-10.,   0.,  10.]])


<details>
<summary>정답 확인</summary>

```python
row_mean = x.mean(dim=1, keepdim=True)
centered = x - row_mean
```

`keepdim=True`를 사용하면 `row_mean`의 shape이 `(2, 1)`이 되어 `(2, 3)`인 `x`와 Broadcasting이 가능하다.

</details>


---

# 10. NumPy와 Tensor 변환

PyTorch Tensor와 NumPy 배열은 서로 쉽게 변환할 수 있다.


In [48]:
import numpy as np

numpy_array = np.array([1, 2, 3])

tensor_from_numpy = torch.from_numpy(numpy_array)

print("NumPy:", numpy_array)
print("Tensor:", tensor_from_numpy)

NumPy: [1 2 3]
Tensor: tensor([1, 2, 3])


In [49]:
tensor = torch.tensor([1.0, 2.0, 3.0])

numpy_from_tensor = tensor.numpy()

print("Tensor:", tensor)
print("NumPy:", numpy_from_tensor)

Tensor: tensor([1., 2., 3.])
NumPy: [1. 2. 3.]


## 메모리 공유 주의

CPU Tensor와 NumPy 배열은 변환 과정에서 메모리를 공유할 수 있다.

한쪽 값을 바꾸면 다른 쪽 값도 바뀔 수 있다.


In [50]:
numpy_array = np.array([1, 2, 3])
tensor = torch.from_numpy(numpy_array)

numpy_array[0] = 100

print("NumPy:", numpy_array)
print("Tensor:", tensor)

NumPy: [100   2   3]
Tensor: tensor([100,   2,   3])


독립적인 복사본이 필요하면 `.copy()` 또는 `.clone()`을 사용한다.


In [51]:
numpy_array = np.array([1, 2, 3])
tensor_copy = torch.from_numpy(numpy_array.copy())

numpy_array[0] = 100

print("NumPy:", numpy_array)
print("복사된 Tensor:", tensor_copy)

NumPy: [100   2   3]
복사된 Tensor: tensor([1, 2, 3])


## GPU Tensor를 NumPy로 변환할 때

NumPy 배열은 CPU 메모리에 존재하므로 GPU Tensor는 먼저 CPU로 옮겨야 한다.

```python
numpy_array = tensor.detach().cpu().numpy()
```

- `detach()`: 연산 그래프에서 분리
- `cpu()`: CPU로 이동
- `numpy()`: NumPy 배열로 변환


---

# 11. 이미지 Tensor의 `(N, C, H, W)`

PyTorch CNN은 일반적으로 4차원 이미지 Tensor를 사용한다.

$$
(N, C, H, W)
$$

- `N`: Batch Size, 한 번에 처리하는 이미지 수
- `C`: Channel 수
- `H`: Height
- `W`: Width

예를 들어 RGB 이미지 8장의 크기가 각각 `32 × 32`라면:

```python
shape = (8, 3, 32, 32)
```


In [52]:
images = torch.randn(8, 3, 32, 32)

print("전체 shape:", images.shape)
print("배치 크기 N:", images.shape[0])
print("채널 수 C:", images.shape[1])
print("높이 H:", images.shape[2])
print("너비 W:", images.shape[3])

전체 shape: torch.Size([8, 3, 32, 32])
배치 크기 N: 8
채널 수 C: 3
높이 H: 32
너비 W: 32


## 이미지 한 장 선택하기


In [53]:
first_image = images[0]

print("배치 전체:", images.shape)
print("첫 번째 이미지:", first_image.shape)

배치 전체: torch.Size([8, 3, 32, 32])
첫 번째 이미지: torch.Size([3, 32, 32])


`images[0]`으로 첫 번째 이미지를 선택하면 배치 차원이 사라져 `(C, H, W)`가 된다.

CNN에 다시 한 장짜리 배치로 넣으려면:

```python
first_image.unsqueeze(0)
```

을 사용하여 `(1, C, H, W)`로 만든다.


In [54]:
first_image_batch = first_image.unsqueeze(0)

print(first_image_batch.shape)

torch.Size([1, 3, 32, 32])


---

# 12. 복사와 메모리 공유

Tensor를 다른 변수에 대입하는 것과 복사하는 것은 다르다.


In [55]:
x = torch.tensor([1, 2, 3])
y = x

y[0] = 100

print("x:", x)
print("y:", y)

x: tensor([100,   2,   3])
y: tensor([100,   2,   3])


`y = x`는 새 Tensor를 만든 것이 아니라 같은 Tensor를 가리킨다.

독립적인 Tensor를 만들려면 `clone()`을 사용한다.


In [56]:
x = torch.tensor([1, 2, 3])
y = x.clone()

y[0] = 100

print("x:", x)
print("y:", y)

x: tensor([1, 2, 3])
y: tensor([100,   2,   3])


---

# 13. 종합 연습문제

아래 문제를 순서대로 해결해 보자.


## 문제 1. Tensor 생성과 형태 확인

0부터 23까지의 정수를 저장한 Tensor를 만든 뒤 shape을 `(2, 3, 4)`로 변경하자.


In [77]:
# 여기에 코드를 작성하자.
x = torch.arange(24).reshape(2, 3, 4)

print(x)
print("shape:", x.shape if x is not None else None)

tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],

        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]])
shape: torch.Size([2, 3, 4])


## 문제 2. 인덱싱

문제 1에서 만든 Tensor `x`에서 다음 값을 선택하자.

1. 첫 번째 큰 묶음
2. 두 번째 큰 묶음의 첫 번째 행
3. 값 `23`


In [78]:
first_block = x[0]
first_row_of_second_block = x[1][0]
value_23 = x[1][2][3]

print(first_block)
print(first_row_of_second_block)
print(value_23)

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])
tensor([12, 13, 14, 15])
tensor(23)


## 문제 3. 축 순서 변경

shape이 `(10, 28, 28, 1)`인 흑백 이미지 배치를 `(10, 1, 28, 28)`로 변경하자.


In [82]:
images = torch.randn(10, 28, 28, 1)

converted = images.permute(0, -1, 1, 2)

print(converted.shape if converted is not None else None)

torch.Size([10, 1, 28, 28])


## 문제 4. Flatten

shape가 `(8, 3, 32, 32)`인 이미지 배치에서 배치 차원을 유지하고 나머지를 펼쳐 `(8, 3072)`로 만들자.


In [83]:
images = torch.randn(8, 3, 32, 32)

flattened = images.flatten(1)

print(flattened.shape if flattened is not None else None)

torch.Size([8, 3072])


## 문제 5. 행별 정규화 기초

각 행에서 행 평균을 빼자.

결과의 각 행 평균이 0에 가까운지 확인한다.


In [85]:
x = torch.tensor([[1.0, 2.0, 3.0], [10.0, 20.0, 30.0], [-3.0, 0.0, 3.0]])

centered = x - x.mean(dim=1, keepdim=True)

print(centered)
if centered is not None:
    print("각 행의 평균:", centered.mean(dim=1))

tensor([[ -1.,   0.,   1.],
        [-10.,   0.,  10.],
        [ -3.,   0.,   3.]])
각 행의 평균: tensor([0., 0., 0.])


---

# 14. 종합 연습문제 정답

문제를 먼저 풀어본 뒤 확인하자.


In [62]:
# 문제 1
x = torch.arange(24).reshape(2, 3, 4)

print(x)
print("shape:", x.shape)

tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],

        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]])
shape: torch.Size([2, 3, 4])


In [63]:
# 문제 2
first_block = x[0]
first_row_of_second_block = x[1, 0]
value_23 = x[1, 2, 3]

print("첫 번째 큰 묶음:\n", first_block)
print("\n두 번째 큰 묶음의 첫 번째 행:", first_row_of_second_block)
print("\n값 23:", value_23)

첫 번째 큰 묶음:
 tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

두 번째 큰 묶음의 첫 번째 행: tensor([12, 13, 14, 15])

값 23: tensor(23)


In [64]:
# 문제 3
images = torch.randn(10, 28, 28, 1)
converted = images.permute(0, 3, 1, 2)

print(converted.shape)

torch.Size([10, 1, 28, 28])


In [65]:
# 문제 4
images = torch.randn(8, 3, 32, 32)
flattened = images.flatten(start_dim=1)

print(flattened.shape)

torch.Size([8, 3072])


In [66]:
# 문제 5
x = torch.tensor([[1.0, 2.0, 3.0], [10.0, 20.0, 30.0], [-3.0, 0.0, 3.0]])

centered = x - x.mean(dim=1, keepdim=True)

print(centered)
print("각 행의 평균:", centered.mean(dim=1))

tensor([[ -1.,   0.,   1.],
        [-10.,   0.,  10.],
        [ -3.,   0.,   3.]])
각 행의 평균: tensor([0., 0., 0.])


---

# 15. 핵심 정리

## Tensor의 차원

```text
shape에 들어 있는 숫자의 개수 = Tensor의 차원 수
```

예:

```text
(3,)          → 1차원
(2, 3)        → 2차원
(2, 3, 4)     → 3차원
(2, 3, 4, 5)  → 4차원
```

## 자주 사용하는 속성과 함수

| 기능               | 코드                      |
| ------------------ | ------------------------- |
| 차원 수            | `x.ndim`                  |
| 형태               | `x.shape`                 |
| 자료형             | `x.dtype`                 |
| 장치               | `x.device`                |
| 형태 변경          | `x.reshape(...)`          |
| 1차원으로 펼치기   | `x.flatten()`             |
| 차원 추가          | `x.unsqueeze(dim)`        |
| 크기 1인 차원 제거 | `x.squeeze(dim)`          |
| 두 축 교환         | `x.transpose(dim0, dim1)` |
| 축 순서 재배치     | `x.permute(...)`          |
| 자료형 변경        | `x.float()`, `x.long()`   |
| 장치 이동          | `x.to(device)`            |
| 독립 복사          | `x.clone()`               |

## PyTorch 이미지 Tensor

```text
(N, C, H, W)
```

- `N`: Batch
- `C`: Channel
- `H`: Height
- `W`: Width

다음 노트북에서는 Tensor의 자동 미분 기능인 **Autograd**와 간단한 연산 그래프를 학습할 수 있다.
